apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "frontend.fullname" . }}-nginx
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "frontend.labels" . | nindent 4 }}
data:
  default.conf: |
    server {
      listen 80;
      server_name _;
      root /usr/share/nginx/html;
      index index.html;

      location / {
        try_files $uri $uri/ /index.html;
      }

      location /health {
        return 200 'ok';
        add_header Content-Type text/plain;
      }
    }