nameOverride: ""
fullnameOverride: ""

image:
  repository: minio/minio
  tag: "RELEASE.2024-01-16T16-07-38Z"
  pullPolicy: IfNotPresent

replicaCount: 1

service:
  type: ClusterIP
  apiPort: 9000
  consolePort: 9001
  exposeConsole: true

mode:
  dataDir: /data

persistence:
  enabled: true
  storageClassName: ""
  accessModes: ["ReadWriteOnce"]
  size: 10Gi

resources:
  requests:
    cpu: 200m
    memory: 256Mi
  limits:
    cpu: 600m
    memory: 512Mi

auth:
  existingSecret:
    name: minio-secret
    accessKeyKey: accessKey
    secretKeyKey: secretKey

probes:
  liveness:
    enabled: true
    path: /minio/health/live
    initialDelaySeconds: 30
    periodSeconds: 20
    timeoutSeconds: 10
    failureThreshold: 6
  readiness:
    enabled: true
    path: /minio/health/ready
    initialDelaySeconds: 20
    periodSeconds: 20
    timeoutSeconds: 10
    failureThreshold: 6

nodeSelector:
  kubernetes.io/hostname: k3s-w1