apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.secret.name }}
  labels:
    {{- include "common.labels" . | nindent 4 }}
  annotations:
    argocd.argoproj.io/compare-options: IgnoreExtraneous
type: Opaque
stringData:
  {{- range $key, $value := .Values.secret.initialValues }}
  {{ $key }}: {{ $value | quote }}
  {{- end }}